### ISSUE TITLE
Loop doesn't work

### ISSUE THREAD

**Issue by Kohle81** [oronbz/homebridge-omxplayer#10]
In my config I have loop=false, but the player repeats the title.

Here my config:

{
	"platforms": [{
			"platform": "OmxPlayer",
			"name": "Sprachbefehle",
			"playPlaylistSwitch": false,
			"shuffleSwitch": false,
			"repeatAll": false,
			"format": "140",
			"path": "/var/homebridge-omx2/",
			"output": "both",
			"playNextSwitch": false,
			"volumeControl": false,
			"playlist": [{
				"switchName": "Guten Morgen",
				"filename": "/var/homebridge-omx2/GutenMorgen.mp4",
				"loop": false
			}]
		}

	]
}

I want that the title plays one time and then the switch should be closed.

**Comment by seydx** [comment]
Should be fixed with https://github.com/oronbz/homebridge-omxplayer/pull/11/commits/e289ba8965d65d0c6f486e0b22ac2c4dc2d5613d

**Comment by oronbz** [comment]
Fixed by: https://github.com/oronbz/homebridge-omxplayer/pull/11
