### ISSUE TITLE
Is it possible to create a „pause button“

### ISSUE THREAD

**Issue by Kohle81** [oronbz/homebridge-omxplayer#14]
Hi,

I like your omxplayer, it does a great work!!!

I want to ask you, if it would be possible to create a pause button/switch?

**Comment by nitaybz** [comment]
I think so... I'll try to make it when I find the time :)

**Comment by Kohle81** [comment]
Thanks, nice message ;-)

Von meinem iPhone gesendet

**Comment by nitaybz** [comment]
Hey @Kohle81 !
I created the extra switch for you...
can you try install from github:
`npm install -g https://github.com/oronbz/homebridge-omxplayer#pause`

I can't test it at the moment so please if you can try it and tell me if it works...

all you need to do is to add : `"pauseSwitch": true,` to your config and restart

**Comment by Kohle81** [comment]
Wow, this will be fast ;-)

I will try to test the next days and tell you how it works!!

Great, really great.

Von meinem iPhone gesendet

**Comment by nitaybz** [comment]
Hi @Kohle81 !

Thanks a lot for your donation! it is much appreciated!
so I guess the pause button worked as expected? can I close the issue?

**Comment by Kohle81** [comment]
Yes, all is perfect. You can close this issue. Would you integrate the pause-button in the regular plugin? 

Von meinem iPhone gesendet

**Comment by nitaybz** [comment]
Yes... Just did it now... enjoy :)

**Comment by Kohle81** [comment]
Perfect 👍

Von meinem iPhone gesendet
