### ISSUE TITLE
Stream

### ISSUE THREAD

**Issue by mihaelcmrk** [oronbz/homebridge-omxplayer#15]
Is it possible to play mp3 stream from a website?

For example I have a radio stream like this one: http://138.201.248.219:8006/stream.mp3

Now I would like to start and stop playing it with homebridge.

Omx player can play it with the following command:
<pre>omxplayer http://138.201.248.219:8006/stream.mp3</code></pre>
I just don't know if it is possible to play it with homebridge-omxplayer.

Thank You very much,

regards

**Comment by nitaybz** [comment]
use it as a "filename" I think it should work...
