### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by seydx** [oronbz/homebridge-omxplayer#5]
Hello, i have a problem with starting a movie. If i press on a switch, my homebridge crashes and restarts again.. here my log

`Dez 24 21:33:48 raspberrypi homebridge[25764]: /usr/local/lib/node_modules/homebridge-omxplayer/index.js:118
Dez 24 21:33:48 raspberrypi homebridge[25764]:             this.platform.shuffleAccessory._service.getCharacteristic(Characteristic.On).updateValue(false)
Dez 24 21:33:48 raspberrypi homebridge[25764]:                                            ^
Dez 24 21:33:48 raspberrypi homebridge[25764]: TypeError: Cannot read property '_service' of undefined
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at trackAccessory.setOn (/usr/local/lib/node_modules/homebridge-omxplayer/index.js:118:44)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at emitMany (events.js:147:13)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at Characteristic.On.emit (events.js:224:7)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:856:22)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at Array.forEach (<anonymous>)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:801:8)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at emitMany (events.js:147:13)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at HAPServer.emit (events.js:224:7)
Dez 24 21:33:48 raspberrypi homebridge[25764]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Dez 24 21:33:48 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dez 24 21:33:48 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Dez 24 21:33:48 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

ps. running homebridge via systemd, pi as user and already did the steps you have written under "Troubleshooting"

**Comment by oronbz** [comment]
Thanks for letting us know. @nitaybz will take care of this one.

**Comment by nitaybz** [comment]
@SeydX Please try the last version 2.0.1
It should fix the crash

**Comment by seydx** [comment]
Wow, works great thanks... forgot to mention, i also have a problem with the "playPlaylistSwitch" and "playNextSwitch"... i have set both to false, but it dont disappear in Apple Home..

last question ^^
is it possible to change the resolution with the omxplayer parameters --win "x1 y1 x2 y2" ? want to set it to full screen (--win "0 0 1920 1080")

thanks for the great plugin!!

**Comment by nitaybz** [comment]
Thanks! I'm glad I could help

I'll fix the first issue...
the second I'll check

**Comment by nitaybz** [comment]
so first one is solved... the latest version will not force those switches...
but I'll need @oronbz for the second one, cause we are using an external library here...

**Comment by seydx** [comment]
thanks for all, now it works great !

**Comment by nitaybz** [comment]
@SeydX according to what I've seen, the video should play in full screen unless the video quality is low, try a higher resolution video... it might be possible for us to change the quality of the downloaded video... but we are checking it...
Not gonna happen today though as it requires testings...

**Comment by seydx** [comment]
Yes i can confirm.. tried a 30sec ‚Fireplace‘ Video with 4K quality (on youtube) and „loop=true“ 

It shows in fullscreen, but the quality is very baad if i want to play after download :/

**Comment by nitaybz** [comment]
what do you mean? the 4k video quality is bad?

**Comment by seydx** [comment]
The quality after download is not ‚4k‘ anymore

i.e. this video: https://youtu.be/q6vltBRSnG8

After putting this into my config and restart homebridge, it will download the above video...

After download, the quality drops down to 480p (?) so it is not hd or 4k anymore like on youtube

**Comment by nitaybz** [comment]
@SeydX stay tuned... I'm doing this feature now...
4k is not possible but you can get HD ready... 720p

**Comment by seydx** [comment]
@nitabz very nice, thank you very much for the fast response!

**Comment by nitaybz** [comment]
@SeydX install the latest version and check readme first...
I would suggest to try "format": "best" in config.

**Comment by nitaybz** [comment]
@SeydX don't forget to delete your old files first

**Comment by seydx** [comment]
Ok, i‘ll give it a try, thanks

**Comment by seydx** [comment]
Yes the quality has improven a bit... i think, because of my 4k TV i can not expect a super quality ^^

But thanks anyway for th support and all! Great plugin anyway, love it :)

**Comment by nitaybz** [comment]
the maximum quality is 720p if it's available... more than that I think will crash the Raspberry :)

Glad you enjoy it... closing the issue
