### ISSUE TITLE
Player is closed -> Homebridge crash?

### ISSUE THREAD

**Issue by seydx** [oronbz/homebridge-omxplayer#7]
hey at all,

the plugin worked very well in the last days, but today i got this error after closing a video:

Dez 27 18:00:48 raspberrypi homebridge[1509]: /usr/local/lib/node_modules/homebridge-omxplayer/node_modules/node-omxplayer/index.js:108
Dez 27 18:00:48 raspberrypi homebridge[1509]:                         throw new Error('Player is closed.');
Dez 27 18:00:48 raspberrypi homebridge[1509]:                         ^
Dez 27 18:00:48 raspberrypi homebridge[1509]: Error: Player is closed.

And homebridge restarts after that...

**Comment by nitaybz** [comment]
I need more logs... what happened before that? what command did you try to use? did you close a specific video from playlist or just one?
