### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Kohle81** [oronbz/homebridge-omxplayer#8]
Hello,
I can‘t play the mp4-files. When I start homebridge this will be logged:

Jan 05 15:09:21 raspberrypi homebridge[12693]:  
Jan 05 15:09:21 raspberrypi homebridge[12693]: [2018-1-5 15:09:21] Homebridge is running on port 51826.
Jan 05 15:09:26 raspberrypi homebridge[12693]: WARNING: Writing cache to u'/home/homebridge/.cache/youtube-dl/youtube-sigfuncs/js_vflIfz8pB_43.44.json' failed: Traceback (most recent call last):
Jan 05 15:09:26 raspberrypi homebridge[12693]: File "/usr/local/lib/node_modules/homebridge-omxplayer/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/cache.py", line 49, in store
Jan 05 15:09:26 raspberrypi homebridge[12693]: os.makedirs(os.path.dirname(fn))
Jan 05 15:09:26 raspberrypi homebridge[12693]: File "/usr/lib/python2.7/os.py", line 150, in makedirs
Jan 05 15:09:26 raspberrypi homebridge[12693]: makedirs(head, mode)
Jan 05 15:09:26 raspberrypi homebridge[12693]: File "/usr/lib/python2.7/os.py", line 150, in makedirs
Jan 05 15:09:26 raspberrypi homebridge[12693]: makedirs(head, mode)
Jan 05 15:09:26 raspberrypi homebridge[12693]: File "/usr/lib/python2.7/os.py", line 150, in makedirs
Jan 05 15:09:26 raspberrypi homebridge[12693]: makedirs(head, mode)
Jan 05 15:09:26 raspberrypi homebridge[12693]: File "/usr/lib/python2.7/os.py", line 157, in makedirs
Jan 05 15:09:26 raspberrypi homebridge[12693]: mkdir(name, mode)
Jan 05 15:09:26 raspberrypi homebridge[12693]: OSError: [Errno 13] Permission denied: '/home/homebridge'
Jan 05 15:09:29 raspberrypi homebridge[12693]:

**Comment by Kohle81** [comment]
I have tried with....

sudo usermod -a -G video pi

sudo chmod 777 /usr/lib/node_modules/homebridge-omxplayer/node_modules/youtube-dl/bin/youtube-dl

sudo chmod -R 0777 /home/pi

**Comment by nitaybz** [comment]
make sure you have a home directory on your "homebridge" user
/home/{yourUsername}/

and copy the files and folders from the pi user home folder

**Comment by Kohle81** [comment]
I don‘t understand, what you mean with „copy the files“...
Do you mean the mp4-files?

**Comment by nitaybz** [comment]
No, all the files and folders from /home/pi/

**Comment by Kohle81** [comment]
My homebridge works with systemd.

My hombridge folder is /var/homebridge

Could this be the reason?

Thx for your help

Von meinem iPhone gesendet

**Comment by nitaybz** [comment]
my homebridge setup is the same... it doesn't matter...
just make sure you have a folder at /home/homebridge
it's not suppose to be the main homebridge folder but it suppose to be your user home folder

**Comment by Kohle81** [comment]
Ahh, the folder for the mp4 files have to saved in the folder /var/homebridge/music/

for example?

Von meinem iPhone gesendet

**Comment by Kohle81** [comment]
Ok it works!!!

Thx for your help

Von meinem iPhone gesendet

**Comment by nitaybz** [comment]
that not what I meant :) but I'm glad it did the job anyway...
